const LABELS = {
    DASHBOARD: 'Dashboard',
    LINK_DEVICE: 'Link device',
    ABOUT: 'About',
    PHASE: 'Phase',
    CURRENT: 'Current',
    SIGNAL: 'Signal',
    MOTOR: 'Motor',
    AUTO_MODE: 'Auto mode',
    ON: 'On',
    OFF: 'Off',
    DRY_RUN: 'Dry run',
    OVERLOAD: 'Overload',
    LOCK: 'Lock',
    REFRESH: 'Refresh',
    MOBILE_NUMBER: 'Mobile number',
    MOBILE_NUMBER_PLACEHOLDER: 'Enter 10 digit mobile number',
    ADD: 'Add',
    FIELD_NAME: 'Field name',
    ADD_USER: 'Add user',
    SCHEDULE: 'Schedule',
    SET_CURRENT: 'Set current',
    STARTER_TIMER: 'Starter type',
    RELAY_TIMER: 'Relay timer',
    AUTO_MODE_TIMER: 'Auto mode timer',
    ALERT_SETTING: 'Alert setting',
    GET_ALL_INFO: 'Get all info',
    FACTORY_RESET: 'Factory reset',
    UNLINK_DEVICE: 'Unlink device',
    START: 'Start',
    END: 'End',
    STATUS: 'Status',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    UPDATE_MOBILE_NUMBER: 'Update mobile number',
    MIN: 'Min',
    MAX: 'Max',
    MASTER_NUMBER: 'Master Number',
    USER_ONE: 'User 1',
    USER_TWO: 'User 2',
    USER_THREE: 'User 3',
    USER_FOUR: 'User 4',
    USER_FIVE: 'User 5',
    MOTO: 'Our custer is always happy 🙂.',
    JAL_DURGA: 'Jal Durga',
    CALL: 'Call',
    SMS: 'SMS',
    MODE: 'Mode',
    POWER_ON: 'Power on',
    POWER_OFF: 'Power off',
    NOTIFICATIONS: 'Notifications',
    PLEASE_WAIT: 'Please wait...',
    DRY_OVERLOAD_TIMER: 'Dry Overload Timer',
    DRY_RUN_TIMER: 'Dry run timer',
    OVERLOAD_TIMER: 'Overload timer',
    
}